<a href="https://colab.research.google.com/github/Yukyung0622/Colab/blob/master/Ch03.%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EC%8B%A4%EC%8A%B5/4_%EB%94%A5%EB%9F%AC%EB%8B%9D_CNN_%EB%AA%A8%EB%8D%B8_%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
"""
날짜 : 2022/05/10
이름 : 김유경
내용 : 딥러닝 CNN 모델 테스트하기
"""

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets.cifar10 import load_data
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from keras.preprocessing.image import load_img, img_to_array
from PIL import Image
tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>

In [3]:
#데이터 불러오기
(cifar_train_data, cifar_train_label), (cifar_test_data, cifar_test_label) = load_data()

170508288/170498071 [==============================] - 5s 0us/step


In [4]:
#모델학습을 위한 데이터 전처리(정규화)
cifar_train_data2 = cifar_train_data / 255
cifar_test_data2 = cifar_test_data / 255

In [5]:
#데이터 라벨을 범주형(one-hot encoding)으로 변환
cifar_train_label2 = to_categorical(cifar_train_label)
cifar_test_label2 = to_categorical(cifar_test_label)
cifar_train_label2[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [6]:
#외부 학습모델 불러오기
model = load_model('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/cifar_model.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 16, 16, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 16, 16, 64)        36928     
                                                        

In [7]:
#모델 테스트
result = model.evaluate(cifar_test_data2, cifar_test_label2)
result

313/313 [==============================] - 17s 53ms/step - loss: 0.7132 - acc: 0.7649


[0.7131654024124146, 0.7649000287055969]

In [8]:
###############################################################
#이미지 로드 함수 정의
def load_image(filename):
	# load the image
	img = load_img(filename, target_size=(32, 32))
	# convert to array
	img = img_to_array(img)
	# reshape into a single sample with 3 channels
	img = img.reshape(1, 32, 32, 3)
	# prepare pixel data
	img = img.astype('float32')
	img = img / 255.0
	return img

In [9]:
img = load_image('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/32.jpg')
img

array([[[[0.22352941, 0.14509805, 0.10196079],
         [0.22745098, 0.14901961, 0.10588235],
         [0.20784314, 0.13725491, 0.09803922],
         ...,
         [0.2509804 , 0.16862746, 0.20392157],
         [0.22352941, 0.2       , 0.2       ],
         [0.20784314, 0.23529412, 0.20784314]],

        [[0.16862746, 0.10196079, 0.07058824],
         [0.19215687, 0.1254902 , 0.09803922],
         [0.1764706 , 0.11764706, 0.09019608],
         ...,
         [0.39215687, 0.32941177, 0.34117648],
         [0.3647059 , 0.34901962, 0.3372549 ],
         [0.3372549 , 0.35686275, 0.32941177]],

        [[0.14901961, 0.10588235, 0.09803922],
         [0.14117648, 0.09803922, 0.09019608],
         [0.14509805, 0.10196079, 0.09411765],
         ...,
         [0.3647059 , 0.3254902 , 0.32156864],
         [0.38039216, 0.3647059 , 0.3529412 ],
         [0.43137255, 0.43529412, 0.41568628]],

        ...,

        [[0.44705883, 0.38431373, 0.3882353 ],
         [0.41568628, 0.3529412 , 0.3647059 ]

In [10]:
#이미지 모델 테스트
result = model.predict(img)
result.round()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)